
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// الخطوط
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// metadata = head
export const metadata = {
  title: "Elshaer",
  description: "Generated by create next app",
};

// Navbar component بسيط
function Navbar() {
  return (
    <nav style={{ padding: "1rem", background: "#eee" }}>
      <h1 className="text-black">My Navbar</h1>
    </nav>
  );
}

// Footer component بسيط
function Footer() {
  return (
    <footer style={{ padding: "1rem", background: "#eee", marginTop: "auto" }}>
      <p className="text-black">© 2026 Elshaer. All rights reserved.</p>
    </footer>
  );
}
  const isLogedIn = false;

// Root Layout
export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {isLogedIn&&<Navbar />}          {/* فوق كل الصفحات */}
        <main style={{ flex: 1 }}>{children}</main>  {/* محتوى الصفحة */}
        {isLogedIn&&<Footer />}          {/* تحت كل الصفحات */}
      </body>
    </html>
  );
}
